#!/usr/bin/env python3
"""Pin the Ubuntu 18.04 (bionic) i386 packages that make up the Real Linux Lab.

Resolves the dependencies of ROOTS against the bionic + bionic-updates indexes and
writes packages.lock: one "pool/path.deb sha256 size" line per package. build.sh
downloads exactly these files and refuses any whose checksum differs.

Run it again only to update the image:  python3 scripts/linux-image/resolve.py
"""
import lzma
import os
import re
import sys
import urllib.request

MIRROR = 'https://archive.ubuntu.com/ubuntu'
SUITES = ['bionic-updates', 'bionic-security', 'bionic']  # earlier wins
ROOTS = [
    'linux-image-4.15.0-213-generic', 'seabios',
    'libc6', 'bash', 'coreutils', 'grep', 'sed', 'gawk', 'findutils', 'diffutils',
    'xxd', 'file', 'libmagic-mgc', 'nano', 'less', 'busybox-static', 'ncurses-base',
    'tar', 'gzip', 'bc',
]
# Maintainer-script and packaging machinery the live image never runs.
SKIP = {
    'debconf', 'debconf-2.0', 'dpkg', 'perl-base', 'install-info', 'lsb-base', 'adduser', 'passwd',
    'init-system-helpers', 'sensible-utils', 'libpam0g', 'libpam-modules', 'libpam-runtime',
    'linux-modules-4.15.0-213-generic', 'linux-base', 'initramfs-tools', 'linux-initramfs-tool',
    'kmod', 'cpio', 'udev', 'libaudit1', 'libsemanage1', 'base-files', 'gcc-8-base', 'readline-common',
    'dash', 'mime-support', 'debianutils', 'libgpm2', 'tzdata',
}


def index(suite):
    url = f'{MIRROR}/dists/{suite}/main/binary-i386/Packages.xz'
    print('fetching', url, file=sys.stderr)
    with urllib.request.urlopen(url, timeout=120) as r:
        text = lzma.decompress(r.read()).decode('utf-8', 'replace')
    pkgs = {}
    for block in text.split('\n\n'):
        fields = dict(re.findall(r'^([A-Za-z0-9-]+): (.*)$', block, re.M))
        if 'Package' in fields:
            pkgs[fields['Package']] = fields
    return pkgs


def main():
    merged, provides = {}, {}
    for suite in SUITES:
        for name, f in index(suite).items():
            merged.setdefault(name, f)
    for name, f in merged.items():
        for p in re.split(r',\s*', f.get('Provides', '')):
            if p:
                provides.setdefault(p.split()[0], name)

    chosen, todo = {}, list(ROOTS)
    while todo:
        name = todo.pop()
        if name in chosen or name in SKIP:
            continue
        if name not in merged:
            if name in provides:
                todo.append(provides[name])
                continue
            sys.exit(f'unknown package {name}')
        f = merged[name]
        chosen[name] = f
        deps = ', '.join(x for x in (f.get('Pre-Depends'), f.get('Depends')) if x)
        for alt in re.split(r',\s*', deps):
            if not alt:
                continue
            options = [o.strip().split()[0].split(':')[0] for o in alt.split('|')]
            pick = next((o for o in options if o in merged or o in provides), options[0])
            todo.append(pick)

    lock = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'packages.lock')
    with open(lock, 'w') as out:
        out.write('# Generated by resolve.py: <pool path> <sha256> <size>. Do not edit by hand.\n')
        for name in sorted(chosen):
            f = chosen[name]
            out.write(f"{f['Filename']} {f['SHA256']} {f['Size']}\n")
    total = sum(int(chosen[n]['Size']) for n in chosen)
    print(f'{len(chosen)} packages, {total / 1e6:.1f} MB of .debs -> {lock}', file=sys.stderr)


if __name__ == '__main__':
    main()
