// The in-app manual: plain-English pages for every command the course uses.

import type { RefEntry } from './types';

export const REFERENCE: RefEntry[] = [
  // ---------------------------------------------------------------- navigation & files
  {
    name: 'pwd', kind: 'builtin',
    summary: 'Print the directory you are currently in (your “working directory”).',
    usage: 'pwd',
    options: [['-P', 'Show the real path with symlinks resolved']],
    examples: [['pwd', 'Where am I?']],
    related: ['cd', 'ls'],
  },
  {
    name: 'cd', kind: 'builtin',
    summary: 'Change the current directory.',
    usage: 'cd [DIRECTORY]',
    options: [['(none)', 'Go to your home directory'], ['-', 'Go back to the previous directory'], ['..', 'Go up one level']],
    examples: [['cd /var/log', 'Go to an absolute path'], ['cd ..', 'Up one level'], ['cd ~/cases', 'Into cases/ inside your home'], ['cd -', 'Jump back to where you were']],
    related: ['pwd', 'ls'],
  },
  {
    name: 'ls', kind: 'command',
    summary: 'List the contents of a directory.',
    usage: 'ls [OPTIONS] [FILE|DIR...]',
    options: [
      ['-l', 'Long format: permissions, owner, size, date'],
      ['-a', 'Include hidden files (names starting with .)'],
      ['-A', 'Like -a but without . and ..'],
      ['-h', 'Human-readable sizes (1.2K, 4.0M) with -l'],
      ['-t', 'Sort by modification time, newest first'],
      ['-r', 'Reverse the sort order'],
      ['-S', 'Sort by size, largest first'],
      ['-R', 'List subdirectories recursively'],
      ['-d', 'List a directory itself, not its contents'],
      ['-1', 'One name per line'],
      ['-F', 'Mark types: / dirs, * executables, @ links'],
    ],
    examples: [['ls -la', 'Everything here, including hidden files, in detail'], ['ls -lt /var/log', 'Most recently changed logs first'], ['ls -ld /tmp', 'Permissions of /tmp itself']],
    security: 'Attackers love hidden files and directories in /tmp and home folders — `ls -la` is your first look.',
    related: ['find', 'stat', 'tree'],
  },
  {
    name: 'cat', kind: 'command',
    summary: 'Print files to the screen (concatenate them).',
    usage: 'cat [OPTIONS] [FILE...]',
    options: [['-n', 'Number every line'], ['-b', 'Number non-empty lines'], ['-A', 'Show hidden characters: tabs as ^I, line ends as $']],
    examples: [['cat notes.txt', 'Show a file'], ['cat a.log b.log > all.log', 'Join two files into a new one'], ['cat -A suspicious.sh', 'Reveal hidden tabs or Windows line endings']],
    related: ['less', 'head', 'tail'],
  },
  {
    name: 'less', kind: 'command',
    summary: 'View a file page by page. (In this simulator it prints the whole file.)',
    usage: 'less FILE',
    options: [],
    examples: [['less /var/log/syslog', 'Read a long log']],
    related: ['cat', 'head', 'tail'],
  },
  {
    name: 'head', kind: 'command',
    summary: 'Show the first lines of a file (10 by default).',
    usage: 'head [-n N] [FILE...]',
    options: [['-n N', 'Show the first N lines'], ['-N', 'Shortcut for -n N'], ['-n -N', 'Everything except the last N lines'], ['-c N', 'First N bytes']],
    examples: [['head -5 auth.log', 'First five lines'], ['sort -rn counts.txt | head -3', 'Top three results']],
    related: ['tail', 'sort'],
  },
  {
    name: 'tail', kind: 'command',
    summary: 'Show the last lines of a file (10 by default).',
    usage: 'tail [-n N] [FILE...]',
    options: [['-n N', 'Show the last N lines'], ['-n +N', 'Start from line N to the end'], ['-f', 'Follow a growing file (on a real system)']],
    examples: [['tail -n 20 /var/log/auth.log', 'Latest 20 auth events'], ['tail -n +2 users.csv', 'Skip a CSV header']],
    security: 'On a live server `tail -f /var/log/auth.log` watches logins as they happen.',
    related: ['head'],
  },
  {
    name: 'touch', kind: 'command',
    summary: 'Create an empty file, or update a file’s timestamp.',
    usage: 'touch FILE...',
    options: [['-c', 'Don’t create files that don’t exist']],
    examples: [['touch report.txt', 'Create an empty file']],
    related: ['mkdir', 'stat'],
  },
  {
    name: 'mkdir', kind: 'command',
    summary: 'Make directories.',
    usage: 'mkdir [-p] DIR...',
    options: [['-p', 'Create parent directories as needed; no error if it exists'], ['-v', 'Say what was created'], ['-m MODE', 'Set permissions, e.g. -m 700']],
    examples: [['mkdir evidence', 'One directory'], ['mkdir -p cases/2026/march', 'A whole path at once']],
    related: ['rmdir', 'cd'],
  },
  {
    name: 'rmdir', kind: 'command',
    summary: 'Remove empty directories.',
    usage: 'rmdir DIR...',
    options: [],
    examples: [['rmdir old', 'Only works if old/ is empty']],
    related: ['rm'],
  },
  {
    name: 'rm', kind: 'command',
    summary: 'Remove files or directories. There is no recycle bin!',
    usage: 'rm [-r] [-f] FILE...',
    options: [['-r', 'Remove directories and everything inside'], ['-f', 'Never ask, ignore missing files'], ['-i', 'Ask before each removal'], ['-v', 'Say what was removed']],
    examples: [['rm temp.txt', 'Delete a file'], ['rm -r scratch/', 'Delete a directory tree']],
    security: 'During an incident, don’t delete evidence — copy suspicious files somewhere safe first.',
    related: ['rmdir', 'mv'],
  },
  {
    name: 'cp', kind: 'command',
    summary: 'Copy files and directories.',
    usage: 'cp [-r] SOURCE... DEST',
    options: [['-r', 'Copy directories recursively'], ['-p', 'Preserve mode, owner and timestamps'], ['-v', 'Say what was copied'], ['-n', 'Don’t overwrite existing files']],
    examples: [['cp auth.log evidence/', 'Copy into a directory'], ['cp -p config config.bak', 'Back up a file keeping its timestamps']],
    security: 'Use `cp -p` when preserving evidence so timestamps stay intact.',
    related: ['mv', 'rm'],
  },
  {
    name: 'mv', kind: 'command',
    summary: 'Move or rename files.',
    usage: 'mv SOURCE... DEST',
    options: [['-v', 'Say what was moved'], ['-n', 'Don’t overwrite']],
    examples: [['mv draft.txt final.txt', 'Rename'], ['mv *.log logs/', 'Move all logs into a folder']],
    related: ['cp'],
  },
  {
    name: 'ln', kind: 'command',
    summary: 'Create links. `ln -s` makes a symbolic link (a shortcut).',
    usage: 'ln -s TARGET LINKNAME',
    options: [['-s', 'Symbolic link'], ['-f', 'Replace an existing link']],
    examples: [['ln -s /var/log/auth.log auth', 'A shortcut called auth']],
    related: ['ls', 'readlink'],
  },
  {
    name: 'tree', kind: 'command',
    summary: 'Draw a directory as a tree.',
    usage: 'tree [-a] [-d] [-L LEVEL] [DIR]',
    options: [['-a', 'Include hidden files'], ['-d', 'Directories only'], ['-L N', 'Limit depth to N levels']],
    examples: [['tree ~', 'Everything in your home'], ['tree -L 1 /', 'Top level of the system']],
    related: ['ls', 'find'],
  },
  {
    name: 'find', kind: 'command',
    summary: 'Search for files by name, type, size, owner, permissions or age.',
    usage: 'find [PATH...] [TESTS] [ACTIONS]',
    options: [
      ['-name PAT', 'Match file name (use quotes: -name "*.log")'],
      ['-iname PAT', 'Case-insensitive name match'],
      ['-type f|d|l', 'Files, directories or links'],
      ['-user NAME', 'Owned by a user'],
      ['-perm -4000', 'SUID bit set (- means “at least these bits”)'],
      ['-perm -o+w', 'World-writable'],
      ['-mtime -N', 'Modified less than N days ago'],
      ['-mmin -N', 'Modified less than N minutes ago'],
      ['-size +N[kM]', 'Bigger than N (k = KiB, M = MiB)'],
      ['-newer FILE', 'Changed more recently than FILE'],
      ['-empty', 'Empty files/directories'],
      ['-maxdepth N', 'Don’t go deeper than N levels'],
      ['! / -not', 'Negate the next test'],
      ['-o', 'OR between tests'],
      ['-exec CMD {} \\;', 'Run CMD for each result ({} = the path)'],
      ['-print', 'Print the path (the default)'],
    ],
    examples: [
      ['find /var/log -name "*.log"', 'All .log files under /var/log'],
      ['find / -perm -4000 -type f 2>/dev/null', 'SUID programs — a classic audit check'],
      ['find /tmp -mmin -60', 'Anything touched in the last hour'],
      ['find . -name "*.sh" -exec chmod +x {} \\;', 'Make every script executable'],
    ],
    security: 'find is the auditor’s best friend: recently modified files, SUID binaries, world-writable paths and orphaned files all come from find.',
    related: ['ls', 'xargs', 'stat'],
  },
  {
    name: 'stat', kind: 'command',
    summary: 'Show detailed information about a file: size, permissions, owner, timestamps.',
    usage: 'stat [-c FORMAT] FILE...',
    options: [['-c FMT', 'Custom format: %n name, %s size, %a octal perms, %A rwx, %U owner, %y modified']],
    examples: [['stat /etc/passwd', 'Everything about a file'], ["stat -c '%a %U %n' /etc/shadow", 'Octal permissions, owner and name']],
    related: ['ls', 'find'],
  },
  {
    name: 'file', kind: 'command',
    summary: 'Guess what kind of data a file contains (regardless of its name).',
    usage: 'file FILE...',
    options: [['-b', 'Brief: don’t print the file name']],
    examples: [['file invoice.pdf', 'Is it really a PDF?'], ['file *', 'Identify everything here']],
    security: 'Malware often hides behind a harmless extension; `file` looks at the content instead.',
    related: ['xxd', 'strings'],
  },
  {
    name: 'basename', kind: 'command',
    summary: 'Strip the directory (and optionally a suffix) from a path.',
    usage: 'basename PATH [SUFFIX]',
    options: [['-s SUF', 'Remove SUF from each name'], ['-a', 'Several paths']],
    examples: [['basename /var/log/auth.log', '→ auth.log'], ['basename /var/log/auth.log .log', '→ auth']],
    related: ['dirname'],
  },
  {
    name: 'dirname', kind: 'command',
    summary: 'Strip the last part of a path, leaving the directory.',
    usage: 'dirname PATH',
    options: [],
    examples: [['dirname /var/log/auth.log', '→ /var/log']],
    related: ['basename'],
  },
  {
    name: 'realpath', kind: 'command',
    summary: 'Print the full absolute path, with symlinks resolved.',
    usage: 'realpath PATH',
    options: [],
    examples: [['realpath ../notes', 'Turn a relative path into an absolute one']],
    related: ['readlink', 'pwd'],
  },
  {
    name: 'du', kind: 'command',
    summary: 'Show disk usage of files and directories.',
    usage: 'du [-s] [-h] [PATH...]',
    options: [['-s', 'Summary: one total per argument'], ['-h', 'Human-readable sizes']],
    examples: [['du -sh /var/log', 'How big are the logs?']],
    related: ['ls'],
  },

  // ---------------------------------------------------------------- text
  {
    name: 'echo', kind: 'builtin',
    summary: 'Print text.',
    usage: 'echo [-n] [-e] [TEXT...]',
    options: [['-n', 'No newline at the end'], ['-e', 'Interpret escapes like \\n and \\t']],
    examples: [['echo "Hello, $USER"', 'Variables expand inside double quotes'], ["echo 'Price: $5'", 'Single quotes print literally'], ['echo -e "a\\tb"', 'A tab between a and b']],
    related: ['printf'],
  },
  {
    name: 'printf', kind: 'builtin',
    summary: 'Print formatted text — like echo, but precise. Great for tidy reports.',
    usage: 'printf FORMAT [ARGS...]',
    options: [['%s', 'A string'], ['%d', 'An integer'], ['%5s / %-5s', 'Right / left aligned in 5 columns'], ['%.2f', 'A number with 2 decimals'], ['%%', 'A literal %'], ['\\n', 'Newline (printf never adds one itself)'], ['-v VAR', 'Store the result in VAR instead of printing']],
    examples: [["printf '%-15s %5d\\n' \"$ip\" \"$count\"", 'Aligned columns'], ["printf '%s\\n' a b c", 'The format repeats for each argument']],
    related: ['echo'],
  },
  {
    name: 'grep', kind: 'command',
    summary: 'Search text for lines matching a pattern.',
    usage: 'grep [OPTIONS] PATTERN [FILE...]',
    options: [
      ['-i', 'Ignore case'],
      ['-v', 'Invert: lines that do NOT match'],
      ['-c', 'Count matching lines'],
      ['-n', 'Show line numbers'],
      ['-o', 'Print only the matched part'],
      ['-E', 'Extended regex: + ? | () {} without backslashes'],
      ['-F', 'Fixed string — no regex at all'],
      ['-w', 'Whole words only'],
      ['-x', 'Whole line must match'],
      ['-r', 'Search directories recursively'],
      ['-l', 'Only print names of files that match'],
      ['-h / -H', 'Hide / show file names'],
      ['-A N / -B N / -C N', 'Show N lines after / before / around each match'],
      ['-q', 'Quiet: just set the exit status (for if statements)'],
      ['-e PAT', 'Add another pattern'],
    ],
    examples: [
      ['grep "Failed password" /var/log/auth.log', 'Failed SSH logins'],
      ['grep -c "Failed" auth.log', 'How many?'],
      ["grep -oE '([0-9]{1,3}\\.){3}[0-9]{1,3}' auth.log", 'Pull out every IPv4 address'],
      ['grep -v "^#" sshd_config', 'Hide comment lines'],
      ['if grep -q root file; then echo found; fi', 'Use grep as a condition'],
    ],
    security: 'grep is how you find the needle: failed logins, error codes, IOCs, suspicious commands in history files.',
    related: ['awk', 'sed', 'wc'],
  },
  {
    name: 'wc', kind: 'command',
    summary: 'Count lines, words and bytes.',
    usage: 'wc [-l] [-w] [-c] [FILE...]',
    options: [['-l', 'Lines'], ['-w', 'Words'], ['-c', 'Bytes'], ['-m', 'Characters']],
    examples: [['wc -l /var/log/auth.log', 'How many lines?'], ['grep Failed auth.log | wc -l', 'Count matches'], ['wc -l < file', 'Just the number, no file name']],
    related: ['grep'],
  },
  {
    name: 'sort', kind: 'command',
    summary: 'Sort lines of text.',
    usage: 'sort [OPTIONS] [FILE...]',
    options: [
      ['-n', 'Numeric sort (10 after 9)'],
      ['-r', 'Reverse'],
      ['-u', 'Remove duplicates'],
      ['-k N', 'Sort by field N (e.g. -k2,2n)'],
      ['-t C', 'Fields are separated by C'],
      ['-h', 'Human sizes (2K < 1M)'],
      ['-f', 'Ignore case'],
      ['-M', 'Month names (Jan < Feb)'],
    ],
    examples: [['sort -n numbers.txt', 'Smallest first'], ['sort | uniq -c | sort -rn', 'The famous “top N” pipeline'], ['sort -t: -k3,3n /etc/passwd', 'Users by UID']],
    related: ['uniq', 'head'],
  },
  {
    name: 'uniq', kind: 'command',
    summary: 'Collapse ADJACENT duplicate lines (so sort first!).',
    usage: 'uniq [-c] [-d] [-u] [FILE]',
    options: [['-c', 'Prefix each line with how many times it appeared'], ['-d', 'Only lines that were repeated'], ['-u', 'Only lines that were unique'], ['-i', 'Ignore case']],
    examples: [['sort ips.txt | uniq -c', 'Count each IP'], ['sort list | uniq -d', 'Show duplicates']],
    related: ['sort'],
  },
  {
    name: 'cut', kind: 'command',
    summary: 'Cut out columns (fields) or characters from each line.',
    usage: 'cut -d DELIM -f FIELDS [FILE] | cut -c RANGE',
    options: [['-d C', 'Field delimiter (default: tab)'], ['-f LIST', 'Fields to keep: 1 · 1,3 · 2-4 · 3-'], ['-c LIST', 'Characters to keep'], ['-s', 'Skip lines without the delimiter']],
    examples: [['cut -d: -f1 /etc/passwd', 'All usernames'], ["cut -d' ' -f1 access.log", 'First column (client IP)'], ['cut -c1-15 auth.log', 'Just the timestamps']],
    related: ['awk', 'tr'],
  },
  {
    name: 'tr', kind: 'command',
    summary: 'Translate, squeeze or delete characters (reads stdin only).',
    usage: 'tr [-d] [-s] [-c] SET1 [SET2]',
    options: [['a-z A-Z', 'Map one set onto another'], ['-d', 'Delete characters in SET1'], ['-s', 'Squeeze repeats into one'], ['-c', 'Complement: everything NOT in SET1'], ['[:upper:] [:digit:] …', 'Character classes']],
    examples: [['tr a-z A-Z', 'Uppercase'], ["tr -s ' '", 'Squeeze runs of spaces'], ["tr 'A-Za-z' 'N-ZA-Mn-za-m'", 'ROT13 decode'], ["tr -cd '[:print:]'", 'Strip non-printable characters']],
    related: ['sed', 'cut'],
  },
  {
    name: 'sed', kind: 'command',
    summary: 'Stream editor: find-and-replace and line editing on text.',
    usage: "sed [-n] [-E] [-i] 'SCRIPT' [FILE...]",
    options: [
      ["'s/old/new/'", 'Replace the first match on each line'],
      ["'s/old/new/g'", 'Replace every match'],
      ['-E', 'Extended regex'],
      ['-n with p', "Print only selected lines: sed -n '5,10p'"],
      ["'/pat/d'", 'Delete matching lines'],
      ['-i', 'Edit the file in place'],
      ['\\1 \\2 &', 'Back-references and the whole match in replacements'],
    ],
    examples: [["sed 's/yes/no/' file", 'First yes → no on each line'], ["sed -n '/ERROR/p' app.log", 'Like grep'], ["sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' sshd_config", 'Harden a config in place'], ["sed -E 's/([0-9]+\\.){3}[0-9]+/x.x.x.x/g'", 'Redact IP addresses']],
    related: ['grep', 'awk', 'tr'],
  },
  {
    name: 'awk', kind: 'command',
    summary: 'A tiny programming language for column-based text. The log analyst’s power tool.',
    usage: "awk [-F SEP] [-v var=val] 'PATTERN { ACTION }' [FILE...]",
    options: [
      ['$1 $2 … $NF', 'Fields; $0 is the whole line, $NF the last field'],
      ['NR / NF', 'Line number / number of fields'],
      ['-F:', 'Use : as the field separator'],
      ['/regex/ {…}', 'Run the action only on matching lines'],
      ['$3 > 100 {…}', 'Conditions on fields'],
      ['BEGIN {…} / END {…}', 'Run before / after all input'],
      ['count[$1]++', 'Associative arrays — counting made easy'],
      ['printf', 'Formatted output'],
    ],
    examples: [
      ["awk '{print $1}' access.log", 'First column'],
      ["awk -F: '$3 == 0 {print $1}' /etc/passwd", 'Every account with UID 0'],
      ["awk '$9 == 404' access.log", 'Lines where field 9 is 404'],
      ["awk '{bytes += $10} END {print bytes}' access.log", 'Sum a column'],
      ["awk '{c[$1]++} END {for (ip in c) print c[ip], ip}' access.log", 'Count requests per IP'],
    ],
    security: 'Almost every log question is an awk one-liner: who, how many, how much, when.',
    related: ['cut', 'grep', 'sort'],
  },
  {
    name: 'tee', kind: 'command',
    summary: 'Copy input to a file AND to the screen.',
    usage: 'tee [-a] FILE...',
    options: [['-a', 'Append instead of overwrite']],
    examples: [['./audit.sh | tee audit.txt', 'Watch the report and save it']],
    related: ['cat'],
  },
  {
    name: 'xargs', kind: 'command',
    summary: 'Turn input lines into arguments for another command.',
    usage: 'COMMAND | xargs [-n N] [-I {}] OTHER_COMMAND',
    options: [['-n N', 'At most N arguments per run'], ['-I {}', 'Replace {} with each input line'], ['-0', 'Input separated by NUL (pair with find -print0)'], ['-r', 'Don’t run if input is empty']],
    examples: [['find . -name "*.log" | xargs wc -l', 'Line counts of every log'], ['cat ips.txt | xargs -I {} echo "block {}"', 'One command per line']],
    related: ['find'],
  },
  {
    name: 'diff', kind: 'command',
    summary: 'Show the differences between two files.',
    usage: 'diff [-u] FILE1 FILE2',
    options: [['-u', 'Unified format (+ added, - removed)'], ['-q', 'Only say whether they differ'], ['-i', 'Ignore case']],
    examples: [['diff baseline.txt current.txt', 'What changed?'], ['diff -u old.conf new.conf', 'A patch-style view']],
    security: 'Comparing a known-good baseline with today’s state is the heart of integrity monitoring.',
    related: ['comm', 'sha256sum'],
  },
  {
    name: 'comm', kind: 'command',
    summary: 'Compare two SORTED files line by line: only-in-1, only-in-2, in-both.',
    usage: 'comm [-123] FILE1 FILE2',
    options: [['-1', 'Hide lines only in FILE1'], ['-2', 'Hide lines only in FILE2'], ['-3', 'Hide lines in both'], ['-13', 'Show only lines unique to FILE2']],
    examples: [['comm -13 old_users new_users', 'Accounts that appeared since the baseline']],
    related: ['diff', 'sort'],
  },
  {
    name: 'paste', kind: 'command',
    summary: 'Join files side by side, or join lines into one.',
    usage: 'paste [-d DELIM] [-s] FILE...',
    options: [['-d C', 'Delimiter between columns'], ['-s', 'Serial: join all lines of each file into one line']],
    examples: [['paste -sd, ips.txt', 'One comma-separated line']],
    related: ['cut'],
  },
  {
    name: 'rev', kind: 'command',
    summary: 'Reverse each line character by character.',
    usage: 'rev [FILE]',
    options: [],
    examples: [['echo stressed | rev', '→ desserts']],
    related: ['tac'],
  },
  {
    name: 'tac', kind: 'command',
    summary: 'Print a file with its lines in reverse order (cat backwards).',
    usage: 'tac [FILE]',
    options: [],
    examples: [['tac auth.log | head', 'Newest events first']],
    related: ['cat', 'rev'],
  },
  {
    name: 'nl', kind: 'command',
    summary: 'Number the lines of a file.',
    usage: 'nl [-ba] [FILE]',
    options: [['-ba', 'Number blank lines too']],
    examples: [['nl script.sh', 'Line numbers for discussing a script']],
    related: ['cat'],
  },
  {
    name: 'column', kind: 'command',
    summary: 'Line text up in neat columns.',
    usage: 'column -t [-s SEP]',
    options: [['-t', 'Make a table'], ['-s C', 'Input separator']],
    examples: [["column -t -s: /etc/passwd", 'passwd as a table']],
    related: ['printf'],
  },
  {
    name: 'seq', kind: 'command',
    summary: 'Print a sequence of numbers.',
    usage: 'seq [FIRST [STEP]] LAST',
    options: [['-s SEP', 'Separator'], ['-w', 'Pad with zeros to equal width']],
    examples: [['seq 5', '1 to 5'], ['seq 0 10 100', '0, 10, … 100'], ['for i in $(seq 1 3); do …; done', 'Loop a fixed number of times']],
    related: ['for'],
  },
  {
    name: 'expr', kind: 'command',
    summary: 'Old-school arithmetic and string helper. Prefer $(( )) in new scripts.',
    usage: 'expr EXPRESSION',
    options: [],
    examples: [['expr 3 + 4', '→ 7 (spaces required)'], ['expr length "hello"', '→ 5']],
    related: [],
  },

  // ---------------------------------------------------------------- integrity & encoding
  {
    name: 'base64', kind: 'command',
    summary: 'Encode data as Base64 text, or decode it back. Encoding is NOT encryption.',
    usage: 'base64 [-d] [FILE]',
    options: [['-d', 'Decode'], ['-w 0', 'Don’t wrap long lines']],
    examples: [['echo "hello" | base64', '→ aGVsbG8K'], ['echo aGVsbG8K | base64 -d', '→ hello']],
    security: 'Attackers hide commands in Base64 (e.g. `echo …== | base64 -d | bash`). Decode suspicious blobs in logs and cron jobs to see what they really do — never pipe them into a shell.',
    related: ['xxd', 'tr'],
  },
  {
    name: 'xxd', kind: 'command',
    summary: 'Show bytes as hexadecimal, or turn hex back into bytes.',
    usage: 'xxd [-p] [-r] [FILE]',
    options: [['-p', 'Plain hex, no offsets'], ['-r -p', 'Reverse: hex → bytes']],
    examples: [['echo hi | xxd', 'Hex dump'], ['echo 6869 | xxd -r -p', '→ hi']],
    related: ['base64', 'hexdump', 'file'],
  },
  {
    name: 'hexdump', kind: 'command',
    summary: 'Show file bytes in hex. `hexdump -C` is the classic canonical view.',
    usage: 'hexdump -C FILE',
    options: [['-C', 'Canonical hex + ASCII']],
    examples: [['hexdump -C sample.bin | head', 'First bytes of a file']],
    related: ['xxd'],
  },
  {
    name: 'sha256sum', kind: 'command',
    summary: 'Compute a SHA-256 fingerprint of files. Any change to the file changes the hash.',
    usage: 'sha256sum [FILE...] | sha256sum -c LIST',
    options: [['-c FILE', 'Check files against a saved list of hashes'], ['--quiet', 'Only report failures']],
    examples: [['sha256sum /etc/passwd', 'Fingerprint one file'], ['sha256sum /etc/* > baseline.txt', 'Save a baseline'], ['sha256sum -c baseline.txt', 'Verify: OK or FAILED for each file']],
    security: 'Hashes prove integrity: if a config file’s hash changed, someone changed the file. Also used to identify known malware samples.',
    related: ['md5sum', 'sha1sum', 'diff'],
  },
  {
    name: 'md5sum', kind: 'command',
    summary: 'Compute MD5 hashes. Fast but broken for security — fine for spotting accidental changes.',
    usage: 'md5sum [FILE...]',
    options: [['-c FILE', 'Check against a list']],
    examples: [['md5sum file.iso', 'Quick checksum']],
    security: 'MD5 collisions are easy to forge. Use SHA-256 when an attacker might be involved.',
    related: ['sha256sum'],
  },
  {
    name: 'sha1sum', kind: 'command',
    summary: 'Compute SHA-1 hashes (deprecated for security, still common in old tools).',
    usage: 'sha1sum [FILE...]',
    options: [['-c FILE', 'Check against a list']],
    examples: [['sha1sum file', 'SHA-1 fingerprint']],
    related: ['sha256sum'],
  },
  {
    name: 'strings', kind: 'command',
    summary: 'Print readable text hidden inside a binary file.',
    usage: 'strings [-n MIN] FILE',
    options: [['-n N', 'Minimum length (default 4)']],
    examples: [['strings suspicious.bin | grep http', 'URLs inside a sample']],
    related: ['file', 'xxd'],
  },

  // ---------------------------------------------------------------- permissions & users
  {
    name: 'chmod', kind: 'command',
    summary: 'Change file permissions (who can read, write, execute).',
    usage: 'chmod MODE FILE...',
    options: [['u g o a', 'user (owner), group, others, all'], ['+ - =', 'add, remove, set exactly'], ['r w x', 'read, write, execute'], ['755 / 644 / 600', 'Octal: r=4 w=2 x=1, per user/group/others'], ['-R', 'Recursive']],
    examples: [['chmod +x script.sh', 'Make a script executable'], ['chmod 600 secrets.txt', 'Only the owner can read/write'], ['chmod go-w report.txt', 'Remove write from group and others']],
    security: 'World-writable files (o+w) and scripts run by root that others can edit are classic privilege-escalation paths.',
    related: ['chown', 'ls', 'stat'],
  },
  {
    name: 'chown', kind: 'command',
    summary: 'Change who owns a file (needs root).',
    usage: 'chown USER[:GROUP] FILE...',
    options: [['-R', 'Recursive']],
    examples: [['sudo chown mara:mara report.txt', 'Give a file to mara']],
    related: ['chmod', 'chgrp'],
  },
  {
    name: 'id', kind: 'command',
    summary: 'Show your user ID, group ID and groups.',
    usage: 'id [USER]',
    options: [['-u', 'Just the UID'], ['-n', 'Names instead of numbers'], ['-G', 'All group IDs']],
    examples: [['id', 'Who am I, exactly?'], ['id mara', 'Someone else’s groups']],
    security: 'UID 0 means root. Membership in groups like sudo or adm grants extra power.',
    related: ['whoami', 'groups'],
  },
  {
    name: 'whoami', kind: 'command',
    summary: 'Print your username.',
    usage: 'whoami',
    options: [],
    examples: [['whoami', '→ analyst'], ['sudo whoami', '→ root']],
    related: ['id'],
  },
  {
    name: 'groups', kind: 'command',
    summary: 'List the groups a user belongs to.',
    usage: 'groups [USER]',
    options: [],
    examples: [['groups', 'Your groups']],
    related: ['id'],
  },
  {
    name: 'sudo', kind: 'command',
    summary: 'Run one command as root (the administrator).',
    usage: 'sudo COMMAND [ARGS]',
    options: [['-l', 'List what you’re allowed to run']],
    examples: [['sudo cat /etc/shadow', 'Read a root-only file'], ['sudo -l', 'Check your sudo rights']],
    security: 'Every sudo use is logged to auth.log. Check who used sudo and what they ran.',
    related: ['id'],
  },
  {
    name: 'getent', kind: 'command',
    summary: 'Look up entries in system databases like passwd and group.',
    usage: 'getent passwd|group [KEY]',
    options: [],
    examples: [['getent passwd mara', 'Mara’s account line']],
    related: ['id'],
  },

  // ---------------------------------------------------------------- system
  {
    name: 'date', kind: 'command',
    summary: 'Print or format the date and time (UTC here).',
    usage: 'date [+FORMAT] [-d STRING]',
    options: [['+%F', '2026-03-14'], ['+%T', '09:12:01'], ['+%s', 'Seconds since 1970 (epoch)'], ['+%Y%m%d-%H%M', 'Handy for file names'], ['-d STRING', 'Use another date: -d yesterday, -d @1700000000, -d "2026-03-14 09:00"']],
    examples: [['date +%F', 'Today’s date'], ['echo "report-$(date +%Y%m%d).txt"', 'Date-stamped file name'], ['date -d @1710400000', 'Convert an epoch timestamp']],
    related: ['sleep'],
  },
  {
    name: 'sleep', kind: 'command',
    summary: 'Wait for a number of seconds.',
    usage: 'sleep N[s|m|h]',
    options: [],
    examples: [['sleep 2', 'Pause two seconds'], ['while true; do date; sleep 5; done', 'A simple monitor loop (stop with ^C)']],
    related: ['date'],
  },
  {
    name: 'ps', kind: 'command',
    summary: 'List running processes.',
    usage: 'ps [aux | -ef]',
    options: [['aux', 'Every process, every user, with CPU/memory'], ['-ef', 'Every process, full format']],
    examples: [['ps aux', 'Everything that’s running'], ['ps aux | grep -v grep | grep miner', 'Look for a suspicious process']],
    security: 'Unexpected processes — odd names, running from /tmp, owned by www-data — are classic signs of compromise.',
    related: ['kill'],
  },
  {
    name: 'kill', kind: 'command',
    summary: 'Send a signal to a process (by default: please terminate).',
    usage: 'kill [-9] PID',
    options: [['-9', 'Force kill (can’t be ignored)']],
    examples: [['kill 4310', 'Stop process 4310']],
    related: ['ps'],
  },
  {
    name: 'who', kind: 'command',
    summary: 'Show who is logged in right now.',
    usage: 'who',
    options: [],
    examples: [['who', 'Current sessions']],
    related: ['w', 'last'],
  },
  {
    name: 'last', kind: 'command',
    summary: 'Show the history of logins.',
    usage: 'last [-N]',
    options: [['-N', 'Only the last N entries']],
    examples: [['last -10', 'Recent logins'], ['last | grep -v 10.20.', 'Logins from outside the office network']],
    security: 'A login at 3 a.m. from an unknown country is worth a closer look.',
    related: ['who', 'lastb'],
  },
  {
    name: 'crontab', kind: 'command',
    summary: 'View or edit scheduled jobs.',
    usage: 'crontab -l | crontab -e',
    options: [['-l', 'List your cron jobs'], ['-e', 'Edit them'], ['-u USER', 'Another user’s (root only)']],
    examples: [['crontab -l', 'What do I have scheduled?'], ['sudo crontab -l -u root', 'Root’s jobs']],
    security: 'Cron is a favourite persistence trick: attackers add a job that re-downloads their malware every few minutes. Always review /etc/crontab, /etc/cron.d/ and each user’s crontab.',
    related: ['date'],
  },
  {
    name: 'env', kind: 'command',
    summary: 'Show environment variables (or run a command with a changed environment).',
    usage: 'env [VAR=value ...] [COMMAND]',
    options: [],
    examples: [['env | sort', 'All exported variables'], ['env LANG=C sort file', 'Run one command with a different setting']],
    related: ['export', 'printenv'],
  },
  {
    name: 'uname', kind: 'command',
    summary: 'Print system information (kernel name and version).',
    usage: 'uname [-a]',
    options: [['-a', 'Everything'], ['-r', 'Kernel release'], ['-n', 'Hostname']],
    examples: [['uname -a', 'Kernel, hostname, architecture']],
    related: ['hostname'],
  },
  {
    name: 'hostname', kind: 'command',
    summary: 'Print the machine’s name.',
    usage: 'hostname [-I]',
    options: [['-I', 'IP addresses']],
    examples: [['hostname', '→ halden-ws01']],
    related: ['uname'],
  },
  {
    name: 'uptime', kind: 'command',
    summary: 'How long the system has been running, and its load.',
    usage: 'uptime',
    options: [['-p', 'Pretty format']],
    examples: [['uptime', 'Up time and load averages']],
    related: ['ps'],
  },
  {
    name: 'ss', kind: 'command',
    summary: 'Show network sockets — which ports are listening.',
    usage: 'ss -tuln',
    options: [['-t / -u', 'TCP / UDP'], ['-l', 'Listening only'], ['-n', 'Numbers, not names']],
    examples: [['ss -tuln', 'Every listening port on this machine']],
    security: 'An unexpected listening port can be a backdoor. Compare against what you expect to run.',
    related: ['ps'],
  },
  {
    name: 'nano', kind: 'command',
    summary: 'Open a file in the text editor (here: the app’s built-in editor).',
    usage: 'nano FILE',
    options: [],
    examples: [['nano myscript.sh', 'Write a script']],
    related: ['bash'],
  },
  {
    name: 'clear', kind: 'command',
    summary: 'Clear the terminal screen (shortcut: Ctrl-L).',
    usage: 'clear',
    options: [],
    examples: [['clear', 'A fresh screen']],
    related: [],
  },
  {
    name: 'man', kind: 'command',
    summary: 'Show the manual page for a command — like this one.',
    usage: 'man COMMAND',
    options: [],
    examples: [['man grep', 'Open grep’s page']],
    related: ['help', 'type'],
  },
  {
    name: 'bc', kind: 'command',
    summary: 'A calculator that handles decimals.',
    usage: 'echo "EXPRESSION" | bc',
    options: [['scale=N', 'Decimal places for division']],
    examples: [['echo "scale=2; 7/3" | bc', '→ 2.33']],
    related: ['expr'],
  },

  // ---------------------------------------------------------------- shell builtins
  {
    name: 'bash', kind: 'command',
    summary: 'Run a bash script (or a command string with -c).',
    usage: 'bash [-x] [-n] SCRIPT [ARGS] | bash -c "COMMANDS"',
    options: [['-x', 'Trace: print each command before running it (great for debugging)'], ['-n', 'Check syntax only, don’t run'], ['-c STR', 'Run the commands in STR']],
    examples: [['bash snapshot.sh', 'Run a script (no chmod needed)'], ['bash -x snapshot.sh', 'Watch it run step by step']],
    related: ['source', 'chmod'],
  },
  {
    name: 'export', kind: 'builtin',
    summary: 'Make a variable visible to programs and scripts you start.',
    usage: 'export NAME=value',
    options: [['-p', 'List exported variables'], ['-n NAME', 'Un-export']],
    examples: [['export THRESHOLD=5', 'Scripts started from here will see THRESHOLD']],
    related: ['env', 'local'],
  },
  {
    name: 'read', kind: 'builtin',
    summary: 'Read a line of input into variables.',
    usage: 'read [-r] [-p PROMPT] [-a ARRAY] VAR...',
    options: [['-r', 'Raw: backslashes are kept (always use this)'], ['-p TEXT', 'Show a prompt'], ['-a ARR', 'Split into an array'], ['IFS=: read …', 'Split on : instead of spaces']],
    examples: [['read -r -p "Your name: " name', 'Ask the user'], ['while read -r line; do …; done < file', 'Process a file line by line'], ['IFS=, read -r a b c <<< "x,y,z"', 'Split CSV fields']],
    related: ['while', 'mapfile'],
  },
  {
    name: 'test', kind: 'builtin',
    summary: 'Check a condition; also written as [ … ]. Sets $? to 0 (true) or 1 (false).',
    usage: '[ EXPRESSION ]',
    options: [
      ['-f FILE', 'Regular file exists'],
      ['-d DIR', 'Directory exists'],
      ['-e PATH', 'Anything exists'],
      ['-r / -w / -x', 'Readable / writable / executable'],
      ['-s FILE', 'Exists and isn’t empty'],
      ['-z STR / -n STR', 'Empty / non-empty string'],
      ['A = B / A != B', 'String (in)equality'],
      ['-eq -ne -lt -le -gt -ge', 'Number comparisons'],
      ['! EXPR', 'Not'],
    ],
    examples: [['[ -f "$log" ] && echo "found"', 'Does the file exist?'], ['[ "$count" -gt 10 ]', 'Numeric comparison (quote your variables!)']],
    related: ['[[', 'if'],
  },
  {
    name: '[[', kind: 'concept',
    summary: 'Bash’s smarter test. No word-splitting surprises, plus pattern and regex matching.',
    usage: '[[ EXPRESSION ]]',
    options: [['==', 'Glob match: [[ $f == *.log ]]'], ['=~', 'Regex match; captures land in BASH_REMATCH'], ['&& ||', 'Combine conditions inside'], ['< >', 'String ordering']],
    examples: [['[[ $ip =~ ^10\\. ]] && echo internal', 'Regex test'], ['[[ -n $user && $user != root ]]', 'Two conditions']],
    related: ['test', 'if'],
  },
  {
    name: 'local', kind: 'builtin',
    summary: 'Declare a variable that only exists inside the current function.',
    usage: 'local NAME[=value]',
    options: [['-a', 'Array'], ['-A', 'Associative array']],
    examples: [['f() { local count=0; …; }', 'count won’t leak out of f']],
    related: ['declare'],
  },
  {
    name: 'declare', kind: 'builtin',
    summary: 'Declare variables with attributes (arrays, integers, read-only).',
    usage: 'declare [-a|-A|-i|-r|-p] NAME[=value]',
    options: [['-a', 'Indexed array'], ['-A', 'Associative array (key → value)'], ['-i', 'Integer'], ['-r', 'Read-only'], ['-p', 'Print a variable’s definition']],
    examples: [['declare -A fails', 'A map from IP to count'], ['declare -p fails', 'Inspect it']],
    related: ['local', 'readonly'],
  },
  {
    name: 'set', kind: 'builtin',
    summary: 'Turn shell options on or off — most importantly the “strict mode” trio.',
    usage: 'set -euo pipefail',
    options: [['-e', 'Exit when a command fails'], ['-u', 'Error on unset variables'], ['-o pipefail', 'A pipeline fails if any part fails'], ['-x', 'Trace commands (debugging)'], ['set -- a b', 'Replace $1, $2 …']],
    examples: [['set -euo pipefail', 'First line of a robust script'], ['set -x; …; set +x', 'Trace just one section']],
    related: ['trap', 'bash'],
  },
  {
    name: 'trap', kind: 'builtin',
    summary: 'Run a command when the script exits, fails, or is interrupted.',
    usage: "trap 'COMMANDS' EXIT|ERR|INT",
    options: [['EXIT', 'Whenever the script ends'], ['ERR', 'Whenever a command fails'], ['INT', 'On Ctrl-C']],
    examples: [["trap 'rm -f \"$tmp\"' EXIT", 'Always clean up temp files'], ["trap 'echo \"failed at line $LINENO\"' ERR", 'Report where it broke']],
    related: ['set', 'exit'],
  },
  {
    name: 'getopts', kind: 'builtin',
    summary: 'Parse command-line options like -v or -n 5 in your own scripts.',
    usage: 'while getopts "vn:" opt; do case $opt in …; esac; done',
    options: [['letter', 'A flag (-v)'], ['letter:', 'An option with a value (-n 5) → in $OPTARG'], [': prefix', 'Silent mode: you handle errors'], ['$OPTIND', 'Index of the next argument; shift $((OPTIND-1)) afterwards']],
    examples: [['while getopts "t:o:" opt; do …', 'Accept -t THRESHOLD and -o OUTFILE']],
    related: ['shift', 'case'],
  },
  {
    name: 'shift', kind: 'builtin',
    summary: 'Drop $1 and move the other arguments down ($2 becomes $1).',
    usage: 'shift [N]',
    options: [],
    examples: [['while [ $# -gt 0 ]; do echo "$1"; shift; done', 'Walk through all arguments']],
    related: ['getopts'],
  },
  {
    name: 'source', kind: 'builtin',
    summary: 'Run a file in the CURRENT shell (its variables and functions stay). Also written `.`.',
    usage: 'source FILE',
    options: [],
    examples: [['source ./lib.sh', 'Load shared functions']],
    related: ['bash'],
  },
  {
    name: 'exit', kind: 'builtin',
    summary: 'Stop the script with a status: 0 = success, anything else = failure.',
    usage: 'exit [N]',
    options: [],
    examples: [['exit 1', 'Signal an error to whoever ran the script']],
    related: ['return', 'trap'],
  },
  {
    name: 'mapfile', kind: 'builtin',
    summary: 'Read lines into an array (also called readarray).',
    usage: 'mapfile -t ARRAY < FILE',
    options: [['-t', 'Strip the newline from each line']],
    examples: [['mapfile -t ips < blocklist.txt', 'Every line becomes an element']],
    related: ['read'],
  },
  {
    name: 'shopt', kind: 'builtin',
    summary: 'Turn Bash’s optional behaviours on or off.',
    usage: 'shopt -s|-u OPTION',
    options: [['-s', 'Set (turn on)'], ['-u', 'Unset (turn off)'], ['nullglob', 'A glob that matches nothing expands to nothing, not to itself'], ['dotglob', 'Globs also match hidden files'], ['nocasematch', 'case and [[ == ]] ignore upper/lower case']],
    examples: [['shopt -s nullglob; for f in *.log; do echo "$f"; done', 'No .log files means no loop runs at all']],
    related: ['set', 'for'],
  },
  {
    name: 'if', kind: 'concept',
    summary: 'Run commands only when a test command succeeds (exit status 0).',
    usage: 'if COMMAND; then …; elif COMMAND; then …; else …; fi',
    options: [['then', 'Starts the block that runs on success'], ['elif', 'Another test, tried when the earlier ones failed'], ['else', 'Runs when every test failed'], ['fi', 'Ends the if']],
    examples: [['if grep -q "Failed password" auth.log; then echo "failures found"; fi', 'Any command works as the test'], ['if [ -f "$1" ]; then wc -l "$1"; else echo "no such file" >&2; fi', 'With a file test']],
    related: ['test', '[[', 'case'],
  },
  {
    name: 'for', kind: 'concept',
    summary: 'Repeat commands once for each word in a list, or count with a C-style loop.',
    usage: 'for NAME in WORDS…; do …; done      for (( i=0; i<N; i++ )); do …; done',
    options: [['in WORDS', 'Loop over these words (globs and $(…) are expanded first)'], ['"$@"', 'Loop over the script’s arguments'], ['(( … ))', 'C-style counter loop']],
    examples: [['for f in /var/log/*.log; do wc -l "$f"; done', 'Once per file'], ['for (( i=1; i<=3; i++ )); do echo "try $i"; done', 'Count to three']],
    related: ['while', 'break', 'seq'],
  },
  {
    name: 'while', kind: 'concept',
    summary: 'Repeat commands as long as a test command succeeds. until is the opposite: it repeats while the test fails.',
    usage: 'while COMMAND; do …; done',
    options: [['while IFS= read -r line', 'The safe way to read a file line by line'], ['until COMMAND', 'Loop until the command succeeds']],
    examples: [['while IFS= read -r ip; do echo "checking $ip"; done < ips.txt', 'One line at a time'], ['n=0; while (( n < 3 )); do n=$((n+1)); done', 'A counter']],
    related: ['for', 'read', 'break'],
  },
  {
    name: 'case', kind: 'concept',
    summary: 'Pick a branch by matching a word against glob patterns: tidier than a chain of elifs.',
    usage: 'case WORD in PATTERN) …;; PATTERN|PATTERN) …;; *) …;; esac',
    options: [[')', 'Ends a pattern'], [';;', 'Ends a branch'], ['|', 'Either pattern'], ['*)', 'Matches anything: the default branch'], ['esac', 'Ends the case']],
    examples: [['case "$1" in start) echo go;; stop) echo halt;; *) echo "usage: $0 start|stop" >&2; exit 2;; esac', 'A subcommand menu']],
    related: ['if', 'getopts'],
  },
  {
    name: 'break', kind: 'builtin',
    summary: 'Leave a for, while or until loop early. continue skips to the next round instead.',
    usage: 'break [N]      continue [N]',
    options: [['break', 'Stop the loop now'], ['continue', 'Skip the rest of this round and start the next one'], ['N', 'Act on the Nth enclosing loop']],
    examples: [['for f in *.log; do [ -s "$f" ] || continue; head -1 "$f"; done', 'Skip empty files'], ['while read -r line; do [[ $line == END ]] && break; echo "$line"; done < notes.txt', 'Stop at a marker']],
    related: ['for', 'while'],
  },
  {
    name: 'return', kind: 'builtin',
    summary: 'Leave a function and hand back an exit status (0 means success).',
    usage: 'return [STATUS]',
    options: [['(none)', 'Return the status of the last command run'], ['STATUS', 'A number from 0 to 255']],
    examples: [['is_root() { [ "$(id -u)" -eq 0 ]; }', 'A test function returns its last status'], ['check() { [ -r "$1" ] || return 1; wc -l < "$1"; }', 'Bail out early']],
    related: ['exit', 'local'],
  },
  {
    name: 'mktemp', kind: 'command',
    summary: 'Create a new, empty temporary file (or directory) with a unique name and print that name.',
    usage: 'mktemp [-d] [TEMPLATE]',
    options: [['-d', 'Make a directory instead of a file'], ['-p DIR', 'Create it inside DIR'], ['TEMPLATE', 'Name ending in XXX…, e.g. scan.XXXXXX']],
    examples: [['tmp=$(mktemp)', 'Grab a scratch file'], ["tmp=$(mktemp); trap 'rm -f \"$tmp\"' EXIT", 'Scratch file that cleans itself up']],
    security: 'Never use a fixed name like /tmp/out.txt in a script: another user can create it first. mktemp picks an unused name and makes the file readable only by you.',
    related: ['trap', 'rm'],
  },
  {
    name: 'alias', kind: 'builtin',
    summary: 'Create a shortcut for a longer command.',
    usage: "alias NAME='COMMAND'",
    options: [],
    examples: [["alias ll='ls -alF'", 'll now runs ls -alF'], ['alias', 'List aliases']],
    related: ['type'],
  },
  {
    name: 'type', kind: 'builtin',
    summary: 'Tell whether a name is a builtin, a function, an alias or a program.',
    usage: 'type NAME',
    options: [['-t', 'Just the kind']],
    examples: [['type cd', 'cd is a shell builtin']],
    related: ['which', 'man'],
  },
  {
    name: 'which', kind: 'command',
    summary: 'Show the path of the program a command name would run.',
    usage: 'which NAME',
    options: [],
    examples: [['which grep', '→ /usr/bin/grep']],
    related: ['type'],
  },
  {
    name: 'history', kind: 'builtin',
    summary: 'Show the commands you typed this session.',
    usage: 'history [N]',
    options: [['-c', 'Clear history']],
    examples: [['history 20', 'Last 20 commands']],
    security: 'An attacker’s ~/.bash_history can tell you exactly what they did — if they forgot to delete it.',
    related: [],
  },
];

const BY_NAME = new Map(REFERENCE.map((r) => [r.name, r]));
const ALIASES: Record<string, string> = { '[': 'test', help: 'man', readonly: 'declare', continue: 'break', until: 'while', elif: 'if', esac: 'case', egrep: 'grep', fgrep: 'grep', more: 'less', readarray: 'mapfile', '.': 'source', typeset: 'declare', vim: 'nano', vi: 'nano', readlink: 'realpath', sha512sum: 'sha256sum', hd: 'hexdump', printenv: 'env', netstat: 'ss', w: 'who', lastb: 'last', gawk: 'awk', chgrp: 'chown', tput: 'printf' };

export function lookupRef(name: string): RefEntry | undefined {
  return BY_NAME.get(name) ?? BY_NAME.get(ALIASES[name] ?? '');
}
